import os
import numpy as np
from utils import load_data, evaluate_clustering, generate_html_report
from envelope_clusterer import ImprovedRuleEnvelopeClusterer

def main():
    print("Loading data with full 13 expanded features...")
    # Load 13 features
    X, y_true, files, class_names = load_data("dummy_audio", use_all_features=True)

    # Match the order generated by `extract_features` in utils.py
    feature_names = [
        'dominant_freq', 'rms_energy',
        'low_band_ratio', 'mid_band_ratio', 'high_band_ratio',
        'spectral_flatness', 'spectral_entropy', 'spectral_kurtosis',
        'spectral_centroid', 'temporal_entropy',
        'zcr_mean', 'zcr_std', 'harmonic_score'
    ]

    # Convert numpy array to list of dictionaries required by the envelope clusterer
    X_dicts = []
    for row in X:
        point = {feat: val for feat, val in zip(feature_names, row)}
        X_dicts.append(point)

    print("\nRunning Improved Rule Envelope Clusterer (Adaptive Proximity, 1D overlaps)...")
    # Initialize the clusterer (adaptive_proximity=True by default)
    clusterer = ImprovedRuleEnvelopeClusterer(config_path="ClusteringConfig.yaml")

    # Fit and predict
    y_envelope = clusterer.fit_predict(X_dicts, files)

    metrics_envelope = evaluate_clustering(y_true, y_envelope)
    print("Envelope Clustering Metrics:", metrics_envelope)
    print(f"Number of generated clusters: {len(set(y_envelope))} (Max expected: {clusterer.max_clusters})")

    generate_html_report(
        "05_Rule_Envelope_Clustering",
        files, y_true, y_envelope, class_names, metrics_envelope,
        "Improved Rule Envelope Clusterer (13 Features)"
    )

if __name__ == "__main__":
    main()